#!/bin/sh
show_menu(){
normal=`echo "\033[m"`
    menu=`echo "\033[36m"` #Blue
    number=`echo "\033[33m"` #yellow
    bgred=`echo "\033[41m"`
    fgred=`echo "\033[31m"`
YELLOW='\033[1;33m'
printf "${menu}                   K O S A R L A Y              "
cat /data/data/com.termux/files/home/BypassV1/pytransform/KSL | lolcat -a -d 5
   ./Header
    
    printf "\n${menu}▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣${normal}\n"
    printf "\n${menu}▣▣${number} 1)${menu} B Y P A S S  G L O B A L  ${normal}\n\n" | lolcat -a -d 3
    printf "\n${menu}▣▣${number} 2)${menu} C L E A R   L O G ${normal}\n\n" | lolcat -a -d 3
    printf "\n${menu}▣▣${number} 3)${menu} R E S T  G U E S T  ( G L )  ${normal}\n\n" | lolcat -a -d 3
    printf "\n${menu}▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣${normal}\n"
    printf "\n${fgred}Please enter a menu option and enter or ${fgred}x to exit. ${normal}"
    read opt
}

option_picked(){
    msgcolor=`echo "\033[01;31m"` # bold red
    normal=`echo "\033[00;00m"` # normal white
    message=${@:-"${normal}Error: No message passed"}
    printf "${msgcolor}${message}${normal}\n"
}

clear
echo " "
echo " "
show_menu
while [ $opt != '' ]
    do
    if [ $opt = '' ]; then
      exit;
    else
      case $opt in
        1) clear;
            option_picked "P U B G   G L O B A L  B Y P A S S \n";
            printf "S T A R T I N G    B Y P A S S...\n";
            sleep 2
start=`date +%s`
runtime=$((end-start))
normal=`echo "\033[m"`
menu=`echo "\033[36m"` #Blue
    number=`echo "\033[33m"` #yellow
    bgred=`echo "\033[41m"`
    fgred=`echo "\033[31m"`
YELLOW='\033[1;33m'

if [ -d "/data/data/com.termux/files/home/BypassV1/pytransform/mods/Paks" ] 
then
echo "Connected to the  Server......................................................."
sleep 1
echo " Please Wait "
cp -R /storage/emulated/0/Android/data/com.tencent.ig/ /storage/emulated/0/Android &> /dev/null
sleep 2
rm -rf /data/data/com.tencent.ig/app_crashrecord
touch /data/data/com.tencent.ig/files
touch /data/data/com.tencent.ig/app_crashrecord                                                                                                                                                                                                                                  ##Kosarlay
sleep 3
cp -R /data/data/com.termux/files/home/BypassV1/pytransform/mods/Paks/* /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks &> /dev/null
cp -R /data/data/com.termux/files/home/BypassV1/pytransform/SrcVersion.ini /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved &> /dev/null
sleep 4
echo " "
am start -n com.tencent.ig/com.epicgames.ue4.SplashActivity
sleep 60
c=0
PACKAGE='com.tencent.ig'
while [ $(pidof $PACKAGE) ]
do
c=$((c+1))
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/cache
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/vmpcloudconfig.json
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/RoleInfo/RoleInfo.json
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/UpdateInfo
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/ImageDownload
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Pandora
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/Engine
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/StatEventReportedFlag
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PufferTmpDir
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/afd
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/puffer_temp
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/IGH5Cache
rm -rf /data/data/com.tencent.ig/app_crashrecord
touch /data/data/com.tencent.ig/files
touch /data/data/com.tencent.ig/app_crashrecord
printf "\n${fgred}▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣${normal}\n"
printf "${menu}▣▣▣▣▣▣▣▣▣▣"
printf "${menu}Clear Log ${fgred}=> ${normal}$c"
sleep 15
if [ ! $(pidof $PACKAGE) ]; then
break
fi
sleep 1
done
echo " "
sleep 9
end=`date +%s`
runtime=$((end-start))
runmin=$((runtime/60))
echo " "
printf "\n${fgred}▣▣▣▣▣▣▣▣▣▣▣${menu}Total Execution Time : ${fgred}$runmin Minuts ${fgred}▣▣▣▣▣▣▣▣▣▣▣▣▣${normal}\n"
echo " "
rm -rf /storage/emulated/0/Android/data/com.tencent.ig
sleep 3
mv /storage/emulated/0/Android/com.tencent.ig/ /storage/emulated/0/Android/data/
echo " "
printf "${YELLOW}  Client Restored"
echo " "
else
 echo "${YELLOW} Global Support Is Not Available"
fi
            sleep 2
            echo " "
            echo " E X I T I N G   T O  D R I V E R   C O D E "
            sleep 2
            clear
            show_menu;
        ;;       
        2) clear;
            option_picked "L O G    C L E A N E R \n";
            printf "C L E A N I N G  L O G S ...\n";
            sleep 30
            echo " "
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/cache
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/vmpcloudconfig.json
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Logs
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/RoleInfo/RoleInfo.json
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/UpdateInfo
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/ImageDownload
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Pandora
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/Engine
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/StatEventReportedFlag
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/PufferTmpDir
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/afd
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Paks/puffer_temp
rm -rf /storage/emulated/0/Android/data/com.tencent.ig/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/IGH5Cache
rm -rf /data/data/com.tencent.ig/app_crashrecord
touch /data/data/com.tencent.ig/files
touch /data/data/com.tencent.ig/app_crashrecord
            sleep 2
            echo " "
            echo "E X I T I N G   T O   D R I V E R   C O D E "
            sleep 2
            clear
            show_menu;
        ;;
        3) clear;
            option_picked "G U E S T  R E S E T\n";
            printf "R E S E T T I N G   Y O U R   G U E S T  A C C O U N T ...\n";
            echo " "
            GL="/data/data/com.tencent.ig/shared_prefs/device_id.xml"
            kill com.tencent.ig 2> /dev/null
            rm -rf $GL
            echo "<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <string name=\"random\"></string>
    <string name=\"install\"></string>
    <string name=\"uuid\">$RANDOM$RANDOM-$RANDOM-$RANDOM-$RANDOM-$RANDOM$RANDOM$RANDOM</string>
</map>" > $GL
./progress
sleep 2
            echo " "
            echo "E X I T I N G   T O   D R I V E R   C O D E "
            sleep 2
            clear
            show_menu;
        ;;
        x)
        
printf "${YELLOW}Created by :-\n"
printf "\n${YELLOW}________________________________________________________"
printf "\n${fgred} ╔╗╔═╗╔═══╗╔═══╗╔═══╗╔═══╗╔╗───╔═══╗╔╗──╔╗   "
printf "\n${YELLOW} ║║║╔╝║╔═╗║║╔═╗║║╔═╗║║╔═╗║║║───║╔═╗║║╚╗╔╝║   "
printf "\n${fgred} ║╚╝╝─║║─║║║╚══╗║║─║║║╚═╝║║║───║║─║║╚╗╚╝╔╝   "
printf "\n${YELLOW} ║╔╗║─║║─║║╚══╗║║╚═╝║║╔╗╔╝║║─╔╗║╚═╝║─╚╗╔╝─   "
printf "\n${fgred} ║║║╚╗║╚═╝║║╚═╝║║╔═╗║║║║╚╗║╚═╝║║╔═╗║──║║──   "
printf "\n${YELLOW} ╚╝╚═╝╚═══╝╚═══╝╚╝─╚╝╚╝╚═╝╚═══╝╚╝─╚╝──╚╝──   "
printf "\n${fgred}________________________________________________________"
        exit;
        ;;
        \n)exit;
        ;;
        *)clear;
            option_picked "Pick an option from the menu";
            show_menu;
        ;;
      esac
    fi
done
